# Generated by Django 3.0.6 on 2020-08-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80, unique=True)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('street_number', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('design_type', models.CharField(choices=[('concept_design', 'Concept Design'), ('technical_design', 'Technical Design'), ('developed_design', 'Developed Design')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80, unique=True)),
                ('project_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('further_details_1', models.CharField(blank=True, max_length=200)),
                ('further_details_2', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=31)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(choices=[('concept_design', 'Concept Design'), ('technical_design', 'Technical Design'), ('developed_design', 'Developed Design')], max_length=25)),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('default_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Role')),
                ('design_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.DesignCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('çomplete', 'Complete')], max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('approved', 'Approved/Reviewed')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Task')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='design_health.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_health.Role')),
            ],
        ),
    ]
