# Generated by Django 3.1 on 2020-10-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tidp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tidp.tasktype', verbose_name='Task type/form of information'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tidp.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tidp.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tidp.role')),
            ],
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tidp.projectrole'),
            preserve_default=False,
        ),
    ]
