# Generated by Django 3.1 on 2020-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidp', '0002_auto_20201005_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='role',
            new_name='project_role',
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
