# Generated by Django 3.1 on 2020-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidp', '0003_auto_20201005_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['task_type']},
        ),
        migrations.AlterField(
            model_name='projectrole',
            name='status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_sent', max_length=20),
        ),
    ]
